Web/Controllers/AdminController.cs
using AutoMapper;
using Core.DTOs;
using Core.DTOs.Admin;
using Core.Services.UserServices;
using System.Web.Mvc;
using Web.Attributes;

namespace Web.Controllers
{
    [RequireLogin]
    public class AdminController : Controller
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;

        public AdminController(IUserService userService)
        {
            _userService = userService;
            _mapper = DependencyResolver.Current.GetService<IMapper>();
        }

        public ActionResult Index()
        {
            var users = _userService.GetUsers();
            return View(users);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(UserCreateDTO model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var userDTO = _mapper.Map<UserRegisterDTO>(model);
            _userService.Register(userDTO);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var user = _userService.GetById(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var model = _mapper.Map<UserEditDTO>(user);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(UserEditDTO model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var existingUser = _userService.GetById(model.Id);
            if (existingUser == null)
            {
                return HttpNotFound();
            }

            if (string.IsNullOrEmpty(model.Password))
            {
                model.Password = existingUser.PasswordHash;
            }

            _mapper.Map(model, existingUser);

            _userService.Update(existingUser);

            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            var user = _userService.GetById(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            _userService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Web/Controllers/CardController.cs
using AutoMapper;
using Core.DTOs.CardActions;
using Core.DTOs.CardDTOs;
using Core.DTOs.Transfer;
using Core.Models.CardModels;
using Core.Services.CardServices;
using Domain.Entites;
using System.Linq;
using System.Web.Mvc;
using Web.Attributes;

namespace Web.Controllers
{
    [RequireLogin]
    public class CardController : Controller
    {
        private readonly ICardService _cardService;
        private readonly IMapper _mapper;

        public CardController(ICardService cardService)
        {
            _cardService = cardService;
            _mapper = DependencyResolver.Current.GetService<IMapper>();
        }

        [HttpGet]
        public ActionResult Index()
        {
            var cards = _cardService.GetAll();
            return View(cards);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(UpsertCardModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var userDTO = _mapper.Map<CardCreateDTO>(model);
            _cardService.Create(userDTO);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var card = _cardService.GetById(id);
            if (card == null)
                return HttpNotFound();

            var model = _mapper.Map<UpsertCardModel>(card);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(UpsertCardModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var cardDto = _mapper.Map<CardUpdateDTO>(model);
            _cardService.Update(cardDto);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("Card/Delete/{id}")]
        public ActionResult Delete(int id)
        {
            var card = _cardService.GetById(id);
            if (card == null)
            {
                return HttpNotFound();
            }

            _cardService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ExternalTransfer()
        {
            var cards = _cardService.GetAll();
            var model = new ExternalTransferDTO
            {
                Cards = cards.Select(c => new Card
                {
                    Id = c.Id,
                    Name = c.Name
                }).ToList()
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult LocalTransfer()
        {
            var cards = _cardService.GetAll();
            var model = new LocalTransferDTO
            {
                Cards = cards.Select(c => new Card
                {
                    Id = c.Id,
                    Name = c.Name
                }).ToList()
            };

            return View(model);
        }


        [HttpPost]
        public ActionResult ExternalTransfer(ExternalTransferDTO model)
        {
            if (!ModelState.IsValid)
            {
                var cards = _cardService.GetAll();
                model.Cards = cards.Select(c => new Card { Id = c.Id, Name = c.Name }).ToList();
                return View(model);
            }

            var transferResult = _cardService.TransferToAnotherPerson(model);
            if (!transferResult.Success)
            {
                var cards = _cardService.GetAll();
                model.Cards = cards.Select(c => new Card { Id = c.Id, Name = c.Name }).ToList();
                ModelState.AddModelError("", transferResult.Message);
                return View(model);
            }

            return RedirectToAction("ExternalTransferSuccess");
        }


        [HttpPost]
        public ActionResult LocalTransfer(LocalTransferDTO model)
        {
            if (!ModelState.IsValid)
            {
                var cards = _cardService.GetAll();
                ViewBag.Cards = new SelectList(cards, "Id", "Name");
                return View(model);
            }

            var transferResult = _cardService.TransferToLocalCard(model);
            if (!transferResult.Success)
            {
                var cards = _cardService.GetAll();
                ViewBag.Cards = new SelectList(cards, "Id", "Name");
                ModelState.AddModelError("", transferResult.Message);
                return View(model);
            }

            return RedirectToAction("LocalTransferSuccess");
        }


        [HttpGet]
        public ActionResult Withdraw()
        {
            var cards = _cardService.GetAll().ToList();
            var model = new DepositTransferDTO
            {
                Cards = cards
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Withdraw(DepositTransferDTO model)
        {
            if (!ModelState.IsValid)
            {
                model.Cards = _cardService.GetAll().ToList();
                return View(model);
            }

            var withdrawResult = _cardService.Withdraw(model);

            if (!withdrawResult.Success)
            {
                model.Cards = _cardService.GetAll().ToList();
                ModelState.AddModelError("", withdrawResult.Message);
                return View(model);
            }

            return RedirectToAction("WithdrawSuccess");
        }

        [HttpGet]
        public ActionResult Deposit()
        {
            var cards = _cardService.GetAll();
            var model = new DepositTransferDTO
            {
                Cards = cards.Select(c => new Card
                {
                    Id = c.Id,
                    Name = c.Name
                }).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Deposit(DepositTransferDTO model)
        {
            if (!ModelState.IsValid)
            {
                var cards = _cardService.GetAll();
                model.Cards = cards.Select(c => new Card { Id = c.Id, Name = c.Name }).ToList();
                return View(model);
            }

            var result = _cardService.Deposit(model);
            if (!result.Success)
            {
                ModelState.AddModelError("", result.Message);
                var cards = _cardService.GetAll();
                model.Cards = cards.Select(c => new Card { Id = c.Id, Name = c.Name }).ToList();
                return View(model);
            }

            return RedirectToAction("DepositSuccess");
        }

        [HttpGet]
        public ActionResult History()
        {
            var history = _cardService.GetHistory();

            if (history == null || !history.Any())
            {
                return RedirectToAction("Index");
            }

            return View(history);
        }

        [HttpGet]
        public ActionResult LocalTransferSuccess()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ExternalTransferSuccess()
        {
            return View();
        }

        [HttpGet]
        public ActionResult WithdrawSuccess()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DepositSuccess()
        {
            return View();
        }
    }
}

Web/Views/Shared/_Footer.cshtml
<!-- Footer -->
    <div class="container-copyright my-auto">
        <div class="copyright text-center my-auto">
            <span id="copyright">Copyright &copy; Your Website @DateTime.Now.Year</span>
        </div>
    </div>
<!-- End of Footer -->

Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title - Online Banking</title>

    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/fontawesome")

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    @RenderSection("Styles", required: false)
</head>

<body>
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            @Html.Partial("_Sidebar")
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    @Html.Partial("_Topbar")
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                @RenderBody()
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                @Html.Partial("_Footer")
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
    </div>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    @Scripts.Render("~/bundles/allscripts")
    <script src="https://kit.fontawesome.com/b521712646.js" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Views/Shared/_LayoutEmpty.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title - Online Banking</title>

    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/fontawesome")

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    @RenderSection("Styles", required: false)
</head>

<body>
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- Begin Page Content -->
                @RenderBody()
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->

        </div>
        <!-- End of Content Wrapper -->
    </div>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    @Scripts.Render("~/bundles/allscripts")
    <script src="https://kit.fontawesome.com/b521712646.js" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">


    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Views/Shared/_Sidebar.cshtml
<!-- Sidebar -->
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>

<!-- Sidebar - Brand -->
<a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
    <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-dollar"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Online Banking</div>
</a>

<!-- Divider -->
<hr class="sidebar-divider my-0">

<!-- Nav Item - Dashboard -->
<li class="nav-item active">
    <a class="nav-link" href="@Url.Action("Index", "Home")">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Main page</span>
    </a>
</li>

<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
    Actions
</div>

<li class="nav-item">
    <a class="nav-link" href="@Url.Action("Index", "Card")">
        <i class="fas fa-fw fa-credit-card"></i> <!-- Changed to credit card icon -->
        <span>My Cards</span>
    </a>
</li>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
       aria-expanded="false" aria-controls="collapseTwo">
        <i class="fas fa-exchange-alt"></i>
        <span>Transfer</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Options:</h6>
            <a class="collapse-item" href="@Url.Action("ExternalTransfer", "Card")">To another person</a>
            <a class="collapse-item" href="@Url.Action("LocalTransfer", "Card")">To another card</a>
        </div>
    </div>
</li>

<!-- New Card Managing Dropdown -->
<li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCardManaging"
       aria-expanded="false" aria-controls="collapseCardManaging">
        <i class="fas fa-columns"></i>
        <span>Card Managing</span>
    </a>
    <div id="collapseCardManaging" class="collapse" aria-labelledby="headingCardManaging" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Actions:</h6>
            <a class="collapse-item" href="@Url.Action("Deposit", "Card")">Deposit</a>
            <a class="collapse-item" href="@Url.Action("Withdraw", "Card")">Withdraw</a>
        </div>
    </div>
</li>

<!-- Divider -->
<hr class="sidebar-divider">

@if (Helpers.RoleCheck.IsAdmin.IsUserAdmin())
{
    <!-- Heading -->
    <div class="sidebar-heading">
        Admin
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
           aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Managers</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Admin actions:</h6>
                <a class="collapse-item" href="@Url.Action("Index", "Admin")">Manage Users</a>
            </div>
        </div>
    </li>
}

Web/Views/Shared/_Topbar.cshtml
<!-- Topbar -->

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                               placeholder="Search for..." aria-label="Search"
                               aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@Helpers.Checks.GetUserData.GetUserName()</span>
                <img class="img-profile rounded-circle" src="~/Content/img/undraw_profile_2.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
                <a class="dropdown-item" href="@Url.Action("History", "Card")">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    History
                </a>
                <div class="dropdown-divider"></div>
                @if (Helpers.Checks.IsLogged.IsUserLogged())
                {
                    <a class="dropdown-item" href="@Url.Action("LogOut", "User")">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                }
                else
                {
                    <a class="dropdown-item" href="@Url.Action("Login", "User")">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Login
                    </a>
                }
            </div>
        </li>
    </ul>
<!-- End of Topbar -->